### ISSUE TITLE
Ability to Add Current Location

### ISSUE THREAD

**Issue by vontell** [GoodEnoughSoftware/Rally#12]
It should be easy for the user to add their current location. What kind of button / where should we place this? Any thoughts @tpatel1781 ?

**Comment by tpatel1781** [comment]
If possible, we should have the first option in the autocomplete search bar be current location.

**Comment by vontell** [comment]
I don't think we can, since that is a separate activity that we can't really modify.

**Comment by tpatel1781** [comment]
We could have a smaller FAB show up above the add FAB because it is a sub control. But we need to get it to only show once.
